all:
	cd ch15ex01; scan-build --use-cc=clang make
	cd ch15pr01; scan-build --use-cc=clang make
	cd ch15pr02; scan-build --use-cc=clang make
	cd ch15pr03; scan-build --use-cc=clang make
	cd ch15pr04; scan-build --use-cc=clang make
	cd ch15pr05; scan-build --use-cc=clang make

clean:
	cd ch15ex01; make clean
	cd ch15pr01; make clean
	cd ch15pr02; make clean
	cd ch15pr03; make clean
	cd ch15pr04; make clean
	cd ch15pr05; make clean
