/* A triangular number can be generated by the formula:
 *
 *      triangularNumber = n (n + 1) / 2
 *
 * for any integer value of n. For example, the 10th triangular number, 55, can
 * be generated by substituting 10 as the value of n in the preceeding formula.
 * Write a program that generates a table of triangular numbers using the
 * preceeding formula. Have the program generate every 5th triangular number
 * between 5 and 50.
 */

#include <stdio.h>

int main(void) {
  int n, tri_num;

  printf("Table\n");
  printf("  n       tri_num(n)\n");
  printf(" ---     ------------\n");

  for (n = 5; n <= 50; n += 5) {
    tri_num = n * (n + 1) / 2;
    printf(" %2i       %3i\n", n, tri_num);
  }
  return 0;
}
