/*
 * Largest palindrome product
 *
 * Problem 4
 * Published on Friday, 16th November 2001, 06:00 pm; Difficulty rating: 5%
 *
 * A palindromic number reads the same both ways. The largest palindrome made
 * from the product of two 2-digit numbers is 9009 = 91 × 99.
 *
 * Find the largest palindrome made from the product of two 3-digit numbers.
 */

// TODO: Skip low multipliers

#include <stdbool.h>
#include <stdio.h>

#define MAX_DIGITS 3
#define NUMBER_1 999
#define NUMBER_2 999

int gen(int a, int b);
bool palindrome_check(int n);

int gen(int a, int b) {
  int largest_palindrome = 0;

  while (a > 0) {
    int multiplier = b;
    while (multiplier > 0) {
      int product = a * multiplier;
      if (palindrome_check(product)) {
        if (product > largest_palindrome) {
          largest_palindrome = product;
        }
      }
      multiplier -= 1;
    }
    a -= 1;
  }
  return largest_palindrome;
}

bool palindrome_check(int n) {
  int original = n;
  int reverse = 0;

  while (n != 0) {
    int remainder = n % 10;
    reverse = reverse * 10 + remainder;
    n /= 10;
  }

  if (reverse == original) {
    return true;
  }
  return false;
}

int main(void) {
  printf("The largest palindrome generated by two %d digit numbers is: ",
         MAX_DIGITS);
  printf("%d\n", gen(NUMBER_1, NUMBER_2));

  return 0;
}
